apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>My K8s Webserver</title>
    </head>
    <body>
        <h1>Привет из Kubernetes!</h1>
        <p>Этот HTML-файл загружается из ConfigMap.</p>
    </body>
    </html>
  nginx.conf: |
    events {}
    
    http {
      server {
        listen 80;
        location / {
          auth_basic "Restricted Content";
          auth_basic_user_file /etc/nginx/.htpasswd;
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }
